name: AWS S3 Backup
version: '1.2.2'
slug: aws_s3_backup
description: Upload backups to AWS S3
url: https://github.com/maxosprojects/hass-addons
arch:
  - amd64
image: maxosprojects/hass-aws-s3-backup
boot: manual
init: false
startup: once
options:
  aws_access_key:
  aws_secret_access_key:
  bucket_name:
  bucket_region: us-west-2
  storage_class: STANDARD
schema:
  aws_access_key: str
  aws_secret_access_key: password
  bucket_name: str
  bucket_region: list(us-east-1|us-east-2|us-west-1|us-west-2|af-south-1|ap-east-1|ap-south-2|ap-southeast-3|ap-southeast-4|ap-south-1|ap-northeast-3|ap-northeast-2|ap-southeast-1|ap-southeast-2|ap-northeast-1|ca-central-1|eu-central-1|eu-west-1|eu-west-2|eu-south-1|eu-west-3|eu-south-2|eu-north-1|eu-central-2|me-south-1|me-central-1|sa-east-1|us-gov-east-1|us-gov-west-1)
  storage_class: list(STANDARD|REDUCED_REDUNDANCY|STANDARD_IA|ONEZONE_IA|INTELLIGENT_TIERING|GLACIER|DEEP_ARCHIVE)
map:
  - backup:ro
