name: "Grafana Agent"
description: "Grafana Agent"
version: "1.0.0"
homeassistant: 2024.1.3
slug: "grafana_agent"
url: https://github.com/maxosprojects/hass-addons
init: false
arch:
  - amd64
docker_api: true
hassio_role: admin
journald: true
image: maxosprojects/hass-grafana-agent
options:
  gcloud_hosted_logs_id: null
  grafana_cloud_token: null
  containers: []
schema:
  gcloud_hosted_logs_id: str
  grafana_cloud_token: password
  containers:
    - str
